# Generated by Django 4.2.4 on 2023-09-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_roleapplication_certification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleapplication',
            name='certification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='training_goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
