# Generated by Django 5.0.1 on 2024-01-17 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0031_remove_workoutregimen_connection_and_more'),
        ('Training', '0009_workoutcalendar'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('fitness_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnessuser')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnesstrainer')),
                ('workouts', models.ManyToManyField(to='Training.workout')),
            ],
        ),
    ]
