# Generated by Django 4.2.4 on 2023-09-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0015_exerciseset_workoutplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='client',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='exercise_sets',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='ExerciseSet',
        ),
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
    ]
