# Generated by Django 4.2.5 on 2023-09-25 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0025_fitnesstrainer_height_fitnesstrainer_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.DateTimeField(auto_now_add=True)),
                ('fitness_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnessuser')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.gymslot')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnesstrainer')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipmentreservation',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='equipmentreservation',
            name='fitness_user',
        ),
        migrations.RemoveField(
            model_name='equipmentreservation',
            name='timeslot',
        ),
        migrations.RemoveField(
            model_name='equipmentreservation',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='EquipmentReservation',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
