# Generated by Django 4.2.4 on 2023-09-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_roleapplication_certification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleapplication',
            name='certification_link',
        ),
        migrations.RemoveField(
            model_name='roleapplication',
            name='training_goal',
        ),
        migrations.AlterField(
            model_name='roleapplication',
            name='certification',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roleapplication',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
