# Generated by Django 4.2.4 on 2023-09-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_roleapplication_certification_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleapplication',
            name='certification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
