# Generated by Django 5.0.1 on 2024-02-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0014_medicaloverview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalOverview',
        ),
    ]
