# Generated by Django 5.0.1 on 2024-01-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_dailyevents_workouts_workoutplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='workouts',
        ),
        migrations.RemoveField(
            model_name='workoutplandetail',
            name='workout_plan',
        ),
        migrations.RemoveField(
            model_name='workoutplandetail',
            name='workout',
        ),
        migrations.DeleteModel(
            name='DailyEvents',
        ),
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
        migrations.DeleteModel(
            name='WorkoutPlanDetail',
        ),
    ]
