# Generated by Django 4.2.4 on 2023-09-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_roleapplication_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleapplication',
            name='certification',
            field=models.CharField(default='No Certification', max_length=255),
        ),
    ]
