# Generated by Django 4.2.4 on 2023-09-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_roleapplication_certification_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleapplication',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
