# Generated by Django 5.0.1 on 2024-01-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0006_alter_workoutplan_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
