# Generated by Django 4.2.4 on 2023-09-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0019_exercise_exerciseset_weeklyworkoutplan_workoutday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('repetitions', models.CharField(max_length=255)),
                ('sets', models.CharField(max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WWPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnessuser')),
                ('exercises', models.ManyToManyField(through='Members.WorkoutPlanExercise', to='Members.exercise')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnesstrainer')),
            ],
        ),
        migrations.RemoveField(
            model_name='weeklyworkoutplan',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='weeklyworkoutplan',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='weeklyworkoutplanassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='weeklyworkoutplanassignment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='weeklyworkoutplanassignment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutday',
            name='plan',
        ),
        migrations.DeleteModel(
            name='ExerciseSet',
        ),
        migrations.DeleteModel(
            name='WeeklyWorkoutPlan',
        ),
        migrations.DeleteModel(
            name='WeeklyWorkoutPlanAssignment',
        ),
        migrations.DeleteModel(
            name='WorkoutDay',
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='workout_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.wwplan'),
        ),
    ]
