# Generated by Django 5.0.1 on 2024-01-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsHubApp', '0010_sportsequipment_sportscenter_trainer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
