# Generated by Django 5.0.1 on 2024-03-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsHubApp', '0014_inventoryrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
