# Generated by Django 4.2.4 on 2023-09-09 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0004_fitnesstrainer_certification_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnesstrainer',
            name='certification_link',
        ),
        migrations.CreateModel(
            name='TrainerUserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('fitness_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnesstrainer')),
                ('fitness_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnessuser')),
            ],
        ),
    ]
