# Generated by Django 4.2.4 on 2023-09-12 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0020_workoutplanexercise_wwplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WPlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('repetitions', models.CharField(max_length=255)),
                ('sets', models.CharField(max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.exercise')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.wwplan')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkoutPlanExercise',
        ),
        migrations.AlterField(
            model_name='wwplan',
            name='exercises',
            field=models.ManyToManyField(through='Members.WPlanExercise', to='Members.exercise'),
        ),
    ]
