# Generated by Django 5.0.1 on 2024-01-26 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0031_remove_workoutregimen_connection_and_more'),
        ('Training', '0009_workoutcalendar'),
        ('plan', '0002_dailyevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyevents',
            name='workouts',
            field=models.ManyToManyField(blank=True, to='Training.workout'),
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnesstrainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnessuser')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Training.workout')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.workoutplan')),
            ],
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='workouts',
            field=models.ManyToManyField(through='plan.WorkoutPlanDetail', to='Training.workout'),
        ),
    ]
