# Generated by Django 5.0.1 on 2024-01-26 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0031_remove_workoutregimen_connection_and_more'),
        ('Training', '0010_exercise_additional_info_exercise_reps_exercise_sets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutcalendar',
            name='workouts',
        ),
        migrations.RemoveField(
            model_name='workoutcalendar',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='workoutcalendar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='routine',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='client',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='workoutplanset',
            name='workout_plan',
        ),
        migrations.RemoveField(
            model_name='workoutplanset',
            name='workout_set',
        ),
        migrations.RemoveField(
            model_name='workoutroutine',
            name='connection',
        ),
        migrations.AddField(
            model_name='workoutroutine',
            name='creator_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Members.fitnesstrainer'),
        ),
        migrations.AddField(
            model_name='workoutroutine',
            name='creator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Members.fitnessuser'),
        ),
        migrations.AddField(
            model_name='workoutroutine',
            name='exercises',
            field=models.ManyToManyField(related_name='workout_routines', to='Training.exercise'),
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.DeleteModel(
            name='WorkoutCalendar',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
        migrations.DeleteModel(
            name='WorkoutPlanSet',
        ),
        migrations.DeleteModel(
            name='WorkoutSet',
        ),
    ]
