# Generated by Django 4.2.5 on 2023-09-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0024_weeklyplan_weeklyfitnessplan_dailyworkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesstrainer',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnesstrainer',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportstrainer',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportstrainer',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
