# Generated by Django 5.0.1 on 2024-03-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0033_alter_sportstrainer_specialization'),
        ('SportsHubApp', '0013_inventoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_item_name', models.CharField(blank=True, max_length=100)),
                ('quantity_requested', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SportsHubApp.inventoryitem')),
                ('sports_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsHubApp.sportscenter')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.sportstrainer')),
            ],
        ),
    ]
