# Generated by Django 4.2.4 on 2023-08-12 07:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsHubApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='sportscenter',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default=True),
        ),
    ]
