# Generated by Django 5.0.1 on 2024-03-24 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0033_alter_sportstrainer_specialization'),
        ('SportsHubApp', '0015_remove_inventoryrequest_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='SportsHubApp.sportscenter')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_tournaments', to='Members.sportstrainer')),
                ('participants', models.ManyToManyField(blank=True, related_name='tournaments_participated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
