# Generated by Django 4.2.4 on 2023-09-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0009_trainingplanassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesstrainer',
            name='certification_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
