# Generated by Django 4.2.4 on 2023-09-13 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0021_wplanexercise_delete_workoutplanexercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_from', models.DateTimeField()),
                ('reserved_to', models.DateTimeField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.equipment')),
                ('fitness_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Members.fitnesstrainer')),
                ('fitness_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reservations', to='Members.fitnessuser')),
            ],
            options={
                'unique_together': {('equipment', 'reserved_from', 'reserved_to')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.equipment')),
            ],
        ),
        migrations.RemoveField(
            model_name='wplanexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='wplanexercise',
            name='workout_plan',
        ),
        migrations.RemoveField(
            model_name='wwplan',
            name='client',
        ),
        migrations.RemoveField(
            model_name='wwplan',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='wwplan',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='WPlanExercise',
        ),
        migrations.DeleteModel(
            name='WWPlan',
        ),
    ]
