# Generated by Django 4.2.5 on 2023-09-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0026_gymslot_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymslot',
            name='date',
        ),
    ]
