# Generated by Django 5.0.1 on 2024-02-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0031_remove_workoutregimen_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessuser',
            name='medical_conditions_pdf',
            field=models.FileField(blank=True, null=True, upload_to='medical_conditions_pdfs/'),
        ),
        migrations.AddField(
            model_name='fitnessuser',
            name='medical_conditions_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
