# Generated by Django 4.2.5 on 2023-10-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsHubApp', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportscenter',
            name='price_per_slot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
