# Generated by Django 4.2.4 on 2023-09-13 05:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0022_equipment_equipmentreservation_timeslot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentreservation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipmentreservation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipmentreservation',
            name='timeslot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Members.timeslot'),
        ),
        migrations.AddField(
            model_name='equipmentreservation',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Members.fitnesstrainer'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot_number',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmentreservation',
            name='fitness_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Members.fitnessuser'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.RemoveField(
            model_name='equipmentreservation',
            name='fitness_trainer',
        ),
        migrations.RemoveField(
            model_name='equipmentreservation',
            name='reserved_from',
        ),
        migrations.RemoveField(
            model_name='equipmentreservation',
            name='reserved_to',
        ),
    ]
