# Generated by Django 4.2.5 on 2023-10-08 15:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0028_alter_gymslot_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField(default=1, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.equipment')),
                ('fitness_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Members.fitnessuser')),
                ('timeslot', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Members.timeslot')),
                ('trainer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Members.fitnesstrainer')),
            ],
        ),
    ]
