# Generated by Django 5.0.1 on 2024-02-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0032_fitnessuser_medical_conditions_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportstrainer',
            name='specialization',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
