# Generated by Django 4.2.4 on 2023-09-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_roleapplication_certification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleapplication',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='roleapplication',
            name='certification_link',
        ),
        migrations.RemoveField(
            model_name='roleapplication',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='roleapplication',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='roleapplication',
            name='training_goal',
        ),
    ]
