# Generated by Django 4.2.4 on 2023-09-14 10:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0023_alter_equipmentreservation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trainer_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.traineruserconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnessuser')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyFitnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1details', models.TextField(blank=True, null=True)),
                ('day2details', models.TextField(blank=True, null=True)),
                ('day3details', models.TextField(blank=True, null=True)),
                ('day4details', models.TextField(blank=True, null=True)),
                ('day5details', models.TextField(blank=True, null=True)),
                ('day6details', models.TextField(blank=True, null=True)),
                ('day7details', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('fitness_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnessuser')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnesstrainer')),
            ],
        ),
        migrations.CreateModel(
            name='DailyWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField()),
                ('workout_details', models.TextField()),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.weeklyplan')),
            ],
        ),
    ]
