# Generated by Django 4.2.4 on 2023-09-09 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0005_remove_fitnesstrainer_certification_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('exercises', models.TextField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnesstrainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnessuser')),
            ],
        ),
    ]
