# Generated by Django 5.0.1 on 2024-01-09 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0029_equipment_timeslot_equipmentreservation'),
        ('SportsHubApp', '0009_remove_payment_reservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sportscenter',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sports_centers', to='Members.sportstrainer'),
        ),
        migrations.AddField(
            model_name='sportscenter',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='SportsHubApp.sportsequipment'),
        ),
    ]
