# Generated by Django 4.2.4 on 2023-09-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0013_exercise_exerciseset_workoutplan_exerciseset_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseset',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='weeklyworkoutplan',
            name='client',
        ),
        migrations.RemoveField(
            model_name='weeklyworkoutplan',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='weeklyworkoutplan',
            name='workout_details',
        ),
        migrations.RemoveField(
            model_name='workoutday',
            name='workouts',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='client',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseSet',
        ),
        migrations.DeleteModel(
            name='WeeklyWorkoutPlan',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.DeleteModel(
            name='WorkoutDay',
        ),
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
    ]
