# Generated by Django 5.0.1 on 2024-01-17 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0029_equipment_timeslot_equipmentreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('instructions', models.TextField()),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.traineruserconnection')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutRegimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('focus_area', models.CharField(max_length=255)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.traineruserconnection')),
            ],
        ),
    ]
