# Generated by Django 5.0.1 on 2024-01-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0030_nutritionguide_workoutregimen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutregimen',
            name='connection',
        ),
        migrations.DeleteModel(
            name='NutritionGuide',
        ),
        migrations.DeleteModel(
            name='WorkoutRegimen',
        ),
    ]
