# Generated by Django 5.0.1 on 2024-02-11 07:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportsHubApp', '0011_datapoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='SReservation',
        ),
    ]
