# Generated by Django 4.2.4 on 2023-09-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_roleapplication_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleapplication',
            name='certification_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
