# Generated by Django 4.2.4 on 2023-09-11 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0011_trainingplan_amount_trainingplan_created_by_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=255)),
                ('sets', models.PositiveIntegerField()),
                ('repetitions', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('workouts', models.ManyToManyField(to='Members.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyWorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnessuser')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnesstrainer')),
                ('workout_details', models.ManyToManyField(to='Members.workoutday')),
            ],
        ),
    ]
