# Generated by Django 4.2.5 on 2023-09-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0027_remove_gymslot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymslot',
            name='capacity',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
