# Generated by Django 4.2.4 on 2023-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0003_remove_fitnesstrainer_certification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesstrainer',
            name='certification_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
