# Generated by Django 5.0.1 on 2024-01-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0012_nutrition_nutritionplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='calories',
            new_name='calories_per_serving',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='carbohydrates',
            new_name='carbohydrates_per_serving',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='fat',
            new_name='fat_per_serving',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='protein',
            new_name='protein_per_serving',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='serving_size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
