# Generated by Django 5.0.1 on 2024-01-30 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0031_remove_workoutregimen_connection_and_more'),
        ('Training', '0013_rename_calories_nutrition_calories_per_serving_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_overview', to='Members.fitnessuser')),
            ],
        ),
    ]
