# Generated by Django 4.2.4 on 2023-09-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0008_alter_fitnesstrainer_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnesstrainer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.trainingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.fitnessuser')),
            ],
        ),
    ]
