# Generated by Django 4.2.5 on 2023-09-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportsHubApp', '0003_facility_image_sportscenter_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportscenterfacility',
            name='facility',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='SportsCenter',
        ),
        migrations.DeleteModel(
            name='SportsCenterFacility',
        ),
    ]
