# Generated by Django 4.2.4 on 2023-09-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_fitnesstrainer_certification_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnesstrainer',
            name='certification_link',
        ),
    ]
