# Generated by Django 5.0.1 on 2024-01-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0009_workoutcalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
