# Generated by Django 5.0.1 on 2024-02-25 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsHubApp', '0012_rename_reservation_sreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory_images/')),
                ('sports_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='SportsHubApp.sportscenter')),
            ],
        ),
    ]
