# Generated by Django 5.0.1 on 2024-01-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0007_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('Cardio', 'Cardiovascular'), ('Strength', 'Strength Training'), ('Core', 'Core Workouts'), ('Agility', 'Agility and Coordination'), ('MixedModal', 'Mixed Modal')], default='Cardio', max_length=20),
        ),
    ]
